name: Kraken
favicon: null
layout_spectrum: 0.6923442967236042
typography_spectrum: 0.3532414606306702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9652363453060389
  lightness: 0.6589214550331235
  saturation: 0.7195540068205446
  rhythmicContrast: 0.401307322550565
purpose: []
