name: Kraken
favicon: null
layout_spectrum: 0.6923442967236042
typography_spectrum: 0.3532414606306702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3d3d3f'
    - '#a9a7a8'
    - '#878586'
    - '#1c1d22'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
